DoSomething/blink

.eslintrc, app.js, package.json
- Sets up basic Express Js hello world up
- Sets up JS code style check with eslint and latest [@dosomething/eslint-config](https://www.npmjs.com/package/@dosomething/eslint-config)
- A part of Trello ticket https://trello.com/c/BDa88r49/269-blink-basic-stucture-skel
=> Initial setup

README.md, wercker.yml
Integration with Wercker for automated tests.
=> Implement wercker ci

README.md, package.json, wercker.yml, yarn.lock
=> Add code coverage integration with codecov

README.md, api/index.js, api/v1/index.js, app.js, package.json, test/app.test.js, wercker.yml, yarn.lock
Implements simple routing:
| Endpoint                    | Description                 |
| --------------------------- | --------------------------- |
| `GET /`                     | Greetings                   |
| `GET /api`                  | List available API versions |
| `GET /api/v1`               | List V1 endpoints           |
- 👁 
- `npm start`
- Go to http://localhost:5050/
- A part of Trello ticket https://trello.com/c/BDa88r49/269-blink-basic-stucture-skel
=> Basic routing

README.md, app.js, config/env/override-test.js, config/express.js, config/index.js, config/logger.js, package.json, test/api/index.test.js, test/api/v1/index.test.js, test/app.test.js, wercker.yml
- Restructures app config from `app.js` to `config/` directory
- Restructures tests to match corresponding scripts in `api/`
- Introduces `config/env/overrids-%env%.js` scripts to override app configuration
- Improves npm scripts structure and updates README.md correspondently
- Excludes `config/` and `tests/` from code coverage
- Makes test runner start app on random ports
- 👁 
- `npm run all-tests`
- A part of Trello ticket https://trello.com/c/P2iUMWYt/289-13-blink-version-1-0-setup-first-consumer
=> Introduce env-dependent app configuration

lib/Queue.js, queues/RemoteHttpRequestQ.js, test/lib/Queue.test.js, test/queues/RemoteHttpRequestQueue.test.js
- Implements draft stubs for Queue models and their implementation
- Make sure Queue class asserts `BlinkX` RabbitMQ topic exchange
- Make sure `RemoteHttpRequestQ` asserts its own queue and binds it to `BlinkX` exchange.
- A part of Trello ticket https://trello.com/c/P2iUMWYt/289-13-blink-version-1-0-setup-first-consumer
=> Introduce models

config/express.js
- Use PORT env variable for compatibility with Heroku
=> Setup Heroku staging

lib/Initializer.js, messages/CustomerIoWebhookMessage.js, queues/CustomerIoWebhookQ.js, test/queues/CustomerIoWebhookQ.test.js, test/web/controllers/ApiController.test.js, test/web/controllers/WebHooks.test.js, web/blinkWeb.js, web/controllers/ApiController.js, web/controllers/WebHooksController.js
- Implements Customer IO "Email Activity Webhook" integration
- All webhook data is saved to queue "customer-io-webhook"
- Documentation
=> Customer io endpoint

README.md, package.json, yarn.lock
- Add david-dm.org dependencies and dev-dependencies badges:
[![dependencies Status](https://david-dm.org/DoSomething/blink/status.svg)](https://david-dm.org/DoSomething/blink) [![devDependencies Status](https://david-dm.org/DoSomething/blink/dev-status.svg)](https://david-dm.org/DoSomething/blink?type=dev)
- Upgrade koa to major stable (it's out of alpha, YAY!)
- Explicitly specify koa-router version
- Upgrade ava to next minor version and make correspondent configuration changes
- Upgrade all dependencies
=> Project dependencies upgrade

package.json
Fix minor dependencies mistake.
=> Move code coverage tool from deps to devDeps

README.md, config/app.js, package.json, test/web/blinkWeb.test.js, test/web/controllers/ApiController.test.js, test/web/controllers/ToolsController.test.js, test/web/controllers/WebHooks.test.js, web/blinkWeb.js, yarn.lock
- Blink simple HTTP authentication, default user `blink`, password `blink`
- Now with 100% more Doctor Who references
=> Simple HTTP authentication

package.json, yarn.lock
- Minor package upgrades
- Version bump to 1.0.0-alpha
=> Bump 1.0.0-alpha

docker-compose.yml, package.json, wercker.yml, yarn.lock
- Upgrades node version to latest 7.9.0
- Upgrades RabbitMQ to latest 3.6.9 to be consistent with Heroku RabbitMQ cloud provider CloudAMQP
- Upgrades project dependencies
Pivotal [143353695](https://www.pivotaltracker.com/story/show/143353695)
=> [#143353695] Software upgrade

src/app/BlinkWebApp.js, src/messages/MdataMessage.js, src/web/controllers/WebController.js, src/web/controllers/WebHooksWebController.js, test/web/controllers/WebHooksWebController.test.js
- Implements Mobile Commons mdata Message class
- Creates Gambit chatbot / MoCo integration webhook at `/api/v1/webhooks/gambit-chatbot-mdata`
- `yarn web`
- Load test data ingestion
- Concurrency for web process using throng
- Gambit Chatbot Mdata worker
- QOS for Gambit Chatbot Mdata worker
- Retry in Gambit Chatbot Mdata
=> [#143258643] Implements Mobile Commons / Gambit Chatbot webhook and message

.env, .env.example, .gitignore, package.json, start.js, yarn.lock
- Installs [`dotenv`](https://github.com/motdotla/dotenv)
- Provides `.env` example with the recommendation to disable New Relic locally
- `yarn web`
=> Integrate dot env

.env.example, Procfile, config/customerio.js, config/index.js, package.json, src/app/BlinkWorkerApp.js, src/messages/CustomerIoIdentifyMessage.js, src/messages/UserMessage.js, src/queues/CustomerIoUpdateCustomerQ.js, src/workers/CustomerIoUpdateCustomerWorker.js, yarn.lock
- Creates `customer-io-update-customer` worker
- Creates `CustomerIoIdentifyMessage`
- Transforms `UserMessage` to `CustomerIoIdentifyMessage`
- `yarn web`
- `yarn worker customer-io-update-customer`
- Test coverate
Pivotal [143982623](https://www.pivotaltracker.com/story/show/143982623)
Gateway-PHP integration: https://github.com/DoSomething/gateway/pull/74
=> [#143982623] Customer.io update customer worker

src/web/controllers/WebController.js, test/web/controllers/EventsWebController.test.js, test/web/controllers/ToolsWebController.test.js, test/web/controllers/WebHooksWebController.test.js
- Change success HTTP response code from `200 Created` to `202 Accepted`
Fixes #48
=> Change success HTTP response code from 200 to 202

package.json, yarn.lock
=> Chore: Dependencies update

src/messages/CustomerIoIdentifyMessage.js, src/messages/Message.js, src/queues/Queue.js, src/workers/CustomerIoUpdateCustomerWorker.js, src/workers/FetchWorker.js, src/workers/GambitChatbotMdataProxyWorker.js
- Provides helpers to access Message data and metadata
Preparing for unit testing of Northstar User -> C.io identify message transformation.
Pivotal [143353737](https://www.pivotaltracker.com/story/show/143353737)
=> [#143353737] Provide helpers to access Message data and metadata

package.json, wercker.yml
Minor chore: Update Node.js to 7.10.0
=> Chore: Update Node.js to 7.10.0

src/web/controllers/EventsWebController.js, src/web/controllers/ToolsWebController.js, src/web/controllers/WebController.js, src/web/controllers/WebHooksWebController.js
- Logs successfully ingested message
So it's easier to debug messages processed not by blink
=> Log sucesfully ingested message

src/messages/CustomerIoUpdateCustomerMessage.js, test/messages/CustomerIoUpdateCustomerMessage.test.js
=> Hotfix: Fix subscribed_at field

src/web/controllers/WebController.js, src/web/controllers/WebHooksWebController.js, test/web/controllers/WebHooksWebController.test.js
=> Hotfix: change moco webhook http response from 202 to 200

src/messages/UserMessage.js, src/workers/CustomerIoUpdateCustomerWorker.js, test/messages/UserMessage.test.js
=> Hotfix: Exclude mobile only users

src/workers/GambitChatbotMdataProxyWorker.js, test/helpers/MessageFactoryHelper.js, test/workers/GambitChatbotMdataProxyWorker.test.js
=> [Finishes #145641399] Send retry count header to Gambit

package.json, wercker.yml
Major Node.js upgrade to 8.0.0.
=> Chore: Update Node.js to 8.0.0

package.json, wercker.yml
=> Node security update to 8.1.4

package.json
=> Bump 1.1.2

package.json, wercker.yml
Changelog: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.2.1
=> Node update to 8.2.1

src/app/BlinkApp.js, src/app/BlinkWebApp.js, src/queues/UserReportbackEventQ.js, src/queues/UserSignupEventQ.js, src/web/controllers/EventsWebController.js, test/web/controllers/EventsWebController.test.js
- Create /api/v1/events/user-signup event endpoint
- Create user signup event queue and link it to its endpoint
- Create /api/v1/events/user-reportback
- Create user reportback event queue and link it to its endpoint
Pivotal [150022903](https://www.pivotaltracker.com/story/show/150022903)
Closes #95
=> [#150022903] Add /api/v1/events/user-signup event endpoint

package.json, wercker.yml
Minor Node.js upgrade to 8.3.0.
=> Chore: Update Node.js to 8.3.0

package.json, wercker.yml
Minor Node.js upgrade to 8.4.0.
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.4.0
=> Chore: Update Node.js to 8.4.0

.env.example, Procfile, config/gambit.js, src/app/BlinkWorkerApp.js, src/messages/FreeFormMessage.js, src/workers/GambitMessageDataRelayWorker.js, test/helpers/MessageFactoryHelper.js, test/workers/GambitMessageDataRelayWorker.test.js
Relays message level data Twillio -> MoCo -> Blink -> Gambit Convers
- `yarn web`
- `yarn worker gambit-message-data-relay`
Pivotal [150310810](https://www.pivotaltracker.com/story/show/150310810)
Fixes #102
=> Gambit message data relay

src/messages/TwillioStatusCallbackMessage.js, src/queues/MocoMessageDataQ.js, src/workers/GambitMessageDataRelayWorker.js, test/helpers/MessageFactoryHelper.js, test/workers/GambitMessageDataRelayWorker.test.js
- Makes Moco `GambitMessageDataRelayWorker` process only inbound message data
Pivotal [150457692](https://www.pivotaltracker.com/story/show/150457692)
Fixes #109
=> [Finishes #150457692] Implement basic TwillioStatusCallbackMessage

src/workers/GambitMessageDataRelayWorker.js
Somehow both linter and I missed this.
Fix #111.
=> Fixes #111 Type error

src/lib/RabbitManagement.js, src/messages/CustomerIoCampaignSignupPostMessage.js, src/queues/UserSignupPostEventQ.js, src/web/controllers/EventsWebController.js, test/helpers/MessageFactoryHelper.js, test/messages/CustomerIoCampaignSignupMessage.test.js, test/messages/CustomerIoCampaignSignupPostMessage.test.js, test/web/controllers/EventsWebController.test.js
- Validates and sanitizes messages sent to `/api/v1/events/user-signup-post`
- Implements campaign signup post (reportback) to customer.io transformation
Pivotal [150234289](https://www.pivotaltracker.com/story/show/150234289)
=> [Finishes #150234289] Rogue user campaign signup post customer.io event

Procfile, src/app/BlinkWorkerApp.js, src/messages/CampaignSignupPostMessage.js, src/workers/CustomerIoCampaignSignupEventWorker.js, src/workers/CustomerIoCampaignSignupPostWorker.js, src/workers/CustomerIoCampaignSignupWorker.js, src/workers/CustomerIoTrackEventWorker.js, test/messages/CampaignSignupPostMessage.test.js
- Tracks user campaign signup posts (reportbacks) to customer.io
- Extract cio.track() specific functionality to an abstract class
Also:
- Register on thor
- Sign up for any campaign on thor
- Reportback on this campaign
- Make sure your cio staging user has correspondent events: https://fly2.customer.io/env/63547/people/[your-northstar-id]/activity
Also affected by #115.
Pivotal [150496291](https://www.pivotaltracker.com/story/show/150496291)
=> [Finishes #150496291] Send user campaign signup posts (reportback) to customer.io

package.json, wercker.yml
Minor Node.js upgrade to 8.5.0.
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.5.0
=> Chore: Update Node.js to 8.5.0

package.json
=> Bump 1.5.0

package.json
=> Bump 1.6.0

package.json, src/lib/Dequeuer.js, src/lib/Queue.js, test/helpers/HooksHelper.js, test/helpers/MessageFactoryHelper.js, test/lib/Dequeuer.test.js, test/lib/Exchange.test.js, test/lib/Queue.test.js, test/web/controllers/EventsWebController.test.js, test/web/controllers/ToolsWebController.test.js, test/web/controllers/WebHooksWebController.test.js, yarn.lock
- Provides full test coverage of Dequeuer class
- Creates helper to dynamically create and destroy queues for each test
- Ensures all other tests cleanup after themselves
A part of necessary refactoring prior implementing #70.
Pivotal [152113738](https://www.pivotaltracker.com/story/show/152113738)
Ref #70
=> [#152113738] Full test coverage of Dequeuer

package.json
=> Bump 2.0.0-beta.1

package.json
=> Bump 2.0.0-beta.2

.env.example, Procfile, config/index.js, config/twilio.js, package.json, src/app/BlinkApp.js, src/app/BlinkWebApp.js, src/app/BlinkWorkerApp.js, src/messages/CustomerioSmsBroadcastMessage.js, src/queues/CustomerioSmsBroadcastRelayQ.js, src/web/controllers/WebHooksWebController.js, src/workers/CustomerIoSmsBroadcastRelayWorker.js, test/helpers/MessageFactoryHelper.js, test/lib/Queue.test.js, test/queues/CustomerioSmsBroadcastRelayQ.test.js, test/web/controllers/WebHooksWebController.test.js, yarn.lock
- Creates direct integration customer.io -> blink -> (twilio, gambit)
_pending_
_pending_
=> Send Twilio SMS broadcasts from customer.io though blink

package.json, wercker.yml
- Updates Node.js engine to `8.9.1`
- Updates npm engine to `5.5.1`
- Updates yarn engine to `1.3.2` ([bundled](https://github.com/nodejs/docker-node/blob/0d53412448be2ab19616d4a1beb817a6b856840b/8.9/Dockerfile#L43) in docker-node `8.9.1`)
=> Chore: update node to 8.9.1

.env.example, src/workers/GambitCampaignSignupRelayWorker.js
Changes path to `/v2/messages?origin=signup` per https://github.com/DoSomething/gambit-conversations/pull/282
=> Post Signup messages to Conversations v2

package.json
It increases Blink's version to 2.0.2.
=> Bumped version to 2.0.2

package.json
=> bump version 2.0.4

Procfile, README.md, package.json, src/app/BlinkApp.js, src/app/BlinkWebApp.js, src/app/BlinkWorkerApp.js, src/messages/CampaignSignupMessage.js, src/messages/CampaignSignupPostMessage.js, src/messages/CampaignSignupPostReviewMessage.js, src/queues/CustomerIoCampaignSignupPostReviewQ.js, src/web/controllers/EventsWebController.js, src/workers/CustomerIoCampaignSignupPostReviewWorker.js, src/workers/CustomerIoTrackEventWorker.js, test/helpers/MessageFactoryHelper.js, test/integration/web/controllers/EventsWebController.test.js, test/unit/messages/CampaignSignupPostReviewMessage.test.js, test/unit/queues/CustomerIoCampaignSignupPostReviewQ.test.js
It creates a new endpoint `/api/v1/events/user-signup-post-review`. It will generate `campaign_review` events for a given member in C.io when the member's post is reviewed (rejected/approved) by DS staff.
- Run the tests and get no errors:
- `cd` into your local Blink repo.
- `docker-compose up -d`
- `yarn test:full`
- `docker-compose down`
- Reportback on a campaign in G-Con **staging**.
- Make sure a `campaign_signup_post` event is posted for your user in C.io **staging**.
- Using POSTman, send a request to the  `/api/v1/events/user-signup-post-review` endpoint in Blink **staging**.
- The payload should be the same format as the one sent to `/api/v1/events/user-signup-post`, just change the status to `approved`.
```
{
"id": <signup post id>, // required
"signup_id": …
```
=> Campaign Signup Post Review route, queue, and worker.

package.json
=> bump to 2.1.0

package.json
=> bump version 2.2.0

package.json
Getting ready to deploy the Blink's side of the Welcome message feature.
=> Bump to 2.3.0

package.json
=> Bump to 2.3.1

package.json
=> Bump to 2.3.3
