- .eslintignore
NYC code coverage report generates js files, which we don't need to check for correct syntax.
> Exclude code coverage generated files from code style check

- README.md
- docker-compose.yml
- Adds simple RabbitMQ instance for local testing using Docker
- `docker compose up`
- [`localhost:15672`](http://localhost:15672): RabbitMQ management.
Username: `blink`, password: `blink`.
- A part of Trello ticket https://trello.com/c/P2iUMWYt/289-13-blink-version-1-0-setup-first-consumer
> Simplest RabbitMQ via Docker integration

- .eslintrc.yml
- docker-compose.yml
- lib/RabbitManagement.js
- package.json
- test/lib/RabbitManagement.test.js
- wercker.yml
- yarn.lock
- In order to standartize DoSomething toolset this PR replaces [axios](https://github.com/mzabriskie/axios) HTTP client library with [isomorphic fetch](https://github.com/matthew-andrews/isomorphic-fetch) in RabbitManagement
- Makes wercker install packages through `yarn`
- Fixes [`rabbitmq-management`](https://hub.docker.com/_/rabbitmq/) version to 3.6.8
- `npm run all-tests`
Fixes #12.
> Replace axios with isomorphic fetch in RabbitManagement

- config/express.js
- package.json
- test/web/api/index.test.js
- test/web/api/v1/index.test.js
- test/web/blinkWeb.test.js
- web/api/index.js
- web/api/v1/index.js
- web/blinkWeb.js
- yarn.lock
- Refactors project to use [koa 2](https://github.com/koajs/koa/) instead of Expressjs
- `yarn web`
I've decided to give a shot to Koa js as it's much more compatible with latest Node async / await paradigm. You can find food arguments for using Koa in the article ["Why you should consider Koa instead of Express with Node.js"](https://medium.com/@l1ambda/why-you-should-use-koa-with-node-js-7c231a8174fa).
Here're few excerpts:
> Koa really is Express 5.0 in spirit. Koa is from the same people that created Express, and the authors changed the name to avoid upsetting people because of the backward incompatible changes
> Koa and Express use the same modules
> Koa middleware is much simpler and less hacky than Express middleware due to the way middleware flows in a …
> Experiment: Koa 2

- config/env/override-test.js
- config/web.js
- lib/WebController.js
- test/lib/WebController.test.js
- web/blinkWeb.js
Minor:
- differentiate between http server bind port and front-facing port (base URI port)
- omit port 80 in web URIs
- add test coverage for `WebController.fullUrl()`
> Omit port 80 in base uri

- lib/WebController.js
- test/lib/WebController.test.js
Minor: Fix mistake made in #19. The function wasn't recognizing port 80 when it's set through env variables, because env vars are passed as strings.
> Make sure WebController.fullUrl() accepts port from env var

- src/app/BlinkApp.js
- src/queues/GambitChatbotMdataQ.js
- src/web/controllers/WebHooksWebController.js
- Saves data from `/api/v1/webhooks/gambit-chatbot-mdata` to GambitChatbotMdataQ
- `yarn web`
- Load test data ingestion
- Concurrency for web process using throng
- Gambit Chatbot Mdata worker
- QOS for Gambit Chatbot Mdata worker
- Retry in Gambit Chatbot Mdata
> [#143258643] Implements Mobile Commons / Gambit Chatbot queue

- package.json
This makes coverage report more truthful by including all files.
Turned out default `nyc` behavior is to include only explicitly required files.
> Fix code coverage report: include all files

- src/app/BlinkApp.js
- src/app/BlinkWebApp.js
- src/queues/CustomerIoWebhookQ.js
- src/queues/QuasarCustomerIoEmailActivityQ.js
- src/web/controllers/WebHooksWebController.js
- test/queues/CustomerIoWebhookQ.test.js
- test/web/controllers/WebHooksWebController.test.js
- Renames Customer.io email activity integration endpoint from `/api/v1/webhooks/customerio-webhook` to `/api/v1/webhooks/customerio-email-activity`
- Renames `CustomerIoWebhookQ` to `QuasarCustomerIoEmailActivityQ` classes to delegate this queue to Quasar.
- `yarn web`
Pivotal [142860245](https://www.pivotaltracker.com/story/show/142860245)
> [#142860245] Rename customer.io email activity webhook and send it to quasar queue

- package.json
- src/app/BlinkApp.js
- start.js
- yarn.lock
- Utilizes [`throng`](https://github.com/hunterloftis/throng) to spawn web cluster
- `BLINK_CONCURRENCY_WEB=10 node start.js web`
1 standard heroku dyno has 512 Mb of memory. Web process that publishes to rabbit only consumes 110-120 Mb on the peak of load. Makes sense to utilize more memory. Running web cluster of 3 web workers per process is very safe way to increase Blink effectives.
See load test results here: https://docs.google.com/a/dosomething.org/spreadsheets/d/16MTMqV1rouex7_Y8wnt8OuRczs07rBSCCwVuO2Ir1J4/edit?usp=sharing
Pivotal [143443281](https://www.pivotaltracker.com/story/show/143443281)
> [#143443281] Blink web concurrency

- .env.example
- Procfile
- config/gambit.js
- config/index.js
- src/app/BlinkWorkerApp.js
- src/workers/GambitChatbotMdataProxyWorker.js
- Consumes messages from `gambit-chatbot-mdata` queue and proxies them to gambit `/v1/chatbot`
- `yarn run all-tests`
- `yarn worker gambit-chatbot-mdata-proxy`
- `yarn web`
- `
curl -X "POST" "http://localhost:5050/api/v1/webhooks/gambit-chatbot-mdata" \
-H "Content-Type: application/json" \
-u blink:blink \
-d $'{
"keyword": "SHARE",
"phone": "1<YOUR_PHONE>",
"message_id": "841415468",
"profile_id": "<YOUR MOCO ID>"
}'
`
- Or, just text `MIRRORBOT` to 38383
- QOS for Gambit Chatbot Mdata worker
- Retry in Gambit Chatbot Mdata
> [#143258643] Basic Gambit proxy

- .env.example
- config/gambit.js
- src/lib/Exchange.js
- src/workers/GambitChatbotMdataProxyWorker.js
- Limits Gambit concurrency using RabbitMQ [consumer prefetch](https://www.rabbitmq.com/consumer-prefetch.html) functionality
- Set `GAMBIT_PROXY_CONCURRENCY=0` in .env
- `yarn worker gambit-chatbot-mdata-proxy`
- Notice `2017-04-21T19:02:23.025Z app[]: at=debug application=blink env=development code=gambit_concurrency_change worker=GambitChatbotMdataProxyWorker Setting Gambit concurrency to 10`
> [#143258643] Control gambit througput

- src/errors/BlinkRetryError.js
- src/queues/Queue.js
- src/workers/GambitChatbotMdataProxyWorker.js
- Implements basic message retry functionality
- Makes Blink retry requests to Gambit when it returns not 200 or 422
- `yarn web`
- `yarn worker gambit-chatbot-mdata-proxy`
Current settings are to retry 100 times every 2 seconds, but that needs to be moved to env variables or pre-configured per consumer / queue.
> [Finishes #143258643] Basic retry functionality

- src/queues/Queue.js
- test/queues/Queue.test.js
- Gradually increases delay between unsuccessful message processing retries
Blink retry chart: https://docs.google.com/spreadsheets/d/1AECd5YrOXJnYlH7BW9wtPBL2Tqp5Wjd3c0VnYGqA780/edit#gid=0
> Increase delay between retries

- src/app/BlinkWebApp.js
- src/messages/UserRegistrationMessage.js
- src/web/controllers/ApiWebController.js
- src/web/controllers/EventsWebController.js
- src/web/controllers/WebController.js
- test/web/controllers/EventsWebController.test.js
- Creates `/api/v1/events/user-registration`
- Validates incoming message for user registration event
- `yarn web`
- Execute POST
```
curl -X POST \
http://localhost:5050/api/v1/events/user-registration \
-H 'authorization: Basic Ymxpbms6Ymxpbms=' \
-H 'cache-control: no-cache' \
-H 'content-type: application/json' \
-H 'postman-token: daf9eee3-fe85-209f-cae8-1862311bcf95' \
-d '{
"id": "5554eac1a59dbf117e8b4567"
}'
```
Pivotal [143982623](https://www.pivotaltracker.com/story/show/143982623)
> [#143982623] Create basic user registration event endpoint

- src/app/BlinkWebApp.js
- src/messages/Message.js
- src/messages/UserMessage.js
- src/queues/CustomerIoUpdateCustomerQ.js
- src/web/controllers/EventsWebController.js
- test/web/controllers/EventsWebController.test.js
- Changes `/api/v1/events/user-create` so it accepts Northstar User fields, not Northstar user id
- Replaces `UserRegistrationMessage` with `UserMessage`, generic Northstrar User fields message
- Makes `/api/v1/events/user-create` publish  `UserMessage` to `create.user.event` route
- Renames everything userRegistration to userCreate
Pivotal [143982623](https://www.pivotaltracker.com/story/show/143982623)
> [#143982623] Replace UserRegistrationMessage with UserMessage

- src/messages/CustomerIoIdentifyMessage.js
- src/messages/UserMessage.js
- test/web/controllers/EventsWebController.test.js
- Renames `mobilecommons_status` to `mobile_status`
Fixes #53
Ref https://github.com/DoSomething/northstar/pull/575
> Fix #53: rename `mobilecommons_status` to `mobile_status`

- .eslintrc.yml
- config/app.js
- src/workers/GambitChatbotMdataProxyWorker.js
- test/workers/GambitChatbotMdataProxyWorker.test.js
- Suppress message retry when Gambit sends HTTP header `x-blink-retry-suppress: true` (case insensitive)
Pivotal [145882417](https://www.pivotaltracker.com/story/show/145882417)
Fixes #72
> [Finishes #145882417] Implement x-blink-retry-suppress for Gambit proxy worker

- src/workers/GambitChatbotMdataProxyWorker.js
- Fixes incorrect call of `GambitChatbotMdataProxyWorker.checkRetrySuppress()`.
THANKS, @aaronschachter!
Fixes #76
> Fix #76: checkRetrySuppress is not a static call

- src/app/BlinkApp.js
- src/app/BlinkWebApp.js
- src/messages/FreeFormMessage.js
- src/queues/MocoMessageDataQ.js
- src/web/controllers/WebHooksWebController.js
- test/web/controllers/WebHooksWebController.test.js
Creates a weebhook at `/api/v1/webhooks/moco-message-data`. It receives freeformed data and saves it to `moco-message-data` queue.
> Add moco message data webhook and queue

- .eslintrc.js
- package.json
- src/lib/RabbitManagement.js
- src/queues/CustomerIoUpdateCustomerQ.js
- src/queues/FetchQ.js
- src/queues/GambitChatbotMdataQ.js
- src/workers/FetchWorker.js
- src/workers/GambitChatbotMdataProxyWorker.js
- test/workers/GambitChatbotMdataProxyWorker.test.js
- yarn.lock
- This PR replaces `isomorphic-fetch` package with `node-fetch`.
- `yarn web`
- `yarn worker fetch`
Isomorphic fetch provides fetch function through Node's global scope. This opens the possibility to fetch function being required **after** being called.
In fact, fetch worker is affected by this issue now, see https://github.com/DoSomething/blink/pull/98/files#diff-35576d7c3c88818f76aeaac62500c18aR3. I forgot to explicitly require `isomorphic-fetch` in this package, but the worker still works because the package has been required in another file not related to this worker.
Using `node-fetch` to explicitly access `fetch()` and related classes mitigates potential critical error in the code.
Fixes #93
> Chore: replace isomorphic fetch in order to get rid of global variables

- src/app/BlinkApp.js
- src/app/BlinkWebApp.js
- src/queues/UserSignupPostEventQ.js
- src/web/controllers/EventsWebController.js
- test/web/controllers/EventsWebController.test.js
- Renames `/api/v1/events/user-reportback` to `/api/v1/events/user-signup-post`
Campaign reportbacks has been renamed to user signup posts in Rogue: https://github.com/DoSomething/rogue/blob/master/documentation/endpoints/posts.md.
Pivotal [150022903](https://www.pivotaltracker.com/story/show/150022903)
> [#150022903] Rename user reportback to user signup post

- package.json
Pre production release bump to 1.3.0.
Also, looks like I forgot to bump the version to 1.2.0 in package JSON,  even though I create a tag.
> Bump 1.3.0

- src/messages/CustomerIoCampaignSignupEventMessage.js
- src/workers/CustomerIoCampaignSignupEventWorker.js
- test/helpers/MessageFactoryHelper.js
- test/messages/CustomerIoCampaignSignupEventMessage.test.js
- Posts user campaign signups to customer.io
One last concern is we need to double check that the iso date to timestamps transformation accounts for event timezone.
Rogue sends `created_at` field in GMT iso date, for example `2017-09-14T18:27:21+00:00`. This is transformed to unix time as 1505413641. Unix time resolves to `09/14/2017 @ 6:43pm (UTC)`, which seems to be correct.
However, c.io documentation is kind of vague on what timezone is used when segments are being built. Moreover, c.io [documentation](https://learn.customer.io/documentation/dates-timezones.html) is down now, so I'll address this issue in another pull request.
Pivotal [150496291](https://www.pivotaltracker.com/story/show/150496291)
> [#150496291] Send user campaign signups to customer.io

- src/messages/CampaignSignupMessage.js
- src/messages/CampaignSignupPostMessage.js
- src/models/CustomerIoEvent.js
- test/messages/CampaignSignupMessage.test.js
- test/messages/CampaignSignupPostMessage.test.js
Extend signup and signup post customer.io event attributes with `version` to indicate schema changes.
> Extend cio event with optional version attribute

- src/messages/CampaignSignupPostMessage.js
- test/messages/CampaignSignupPostMessage.test.js
- This PR adds hardcoded type field to `campaign_signup_post` events to indicate them as "actions" (previously known as reportbacks). See #125 for more details.
Ref #125
> Add type field to c.io campaign_signup_post events

- package.json
Ooops. Forgot to bump the version in `package.json` for last minor release.
> Bump 1.4.0

- src/messages/CampaignSignupPostMessage.js
- test/messages/CampaignSignupPostMessage.test.js
- Changes default campaign signup post type from action to photo
Fixes #130
Ref #125
> Change default campaign signup post type from action to photo

- src/app/BlinkApp.js
- src/app/BlinkWebApp.js
- src/messages/TwilioStatusCallbackMessage.js
- src/messages/TwillioStatusCallbackMessage.js
- src/queues/MocoMessageDataQ.js
- src/queues/TwilioSmsBroadcastGambitRelayQ.js
- src/web/controllers/WebHooksWebController.js
- test/helpers/MessageFactoryHelper.js
- test/web/controllers/WebHooksWebController.test.js
- Creates `/api/v1/webhooks/twilio-sms-broadcast` webhook
- Creates `twilio-sms-broadcast-gambit-relay` queue
- Saves StatusCallback data from `/api/v1/webhooks/twilio-sms-broadcast` webhook to `twilio-sms-broadcast-gambit-relay`
- Extends `TwilioStatusCallbackMessage` metadata with GET querystring to catch broadcast id
Pivotal [#151266069](https://www.pivotaltracker.com/story/show/000000000)
Ref https://github.com/DoSomething/gambit-conversations/pull/141
> [#151266069] Ingest Twilio sms broadcast data to twilio-sms-broadcast-gambit-relay queue

- Procfile
- src/app/BlinkWorkerApp.js
- src/messages/TwilioStatusCallbackMessage.js
- src/workers/TwilioSmsBroadcastGambitRelayWorker.js
- test/workers/TwilioSmsBroadcastGambitRelayWorker.test.js
-Creates Gambit broadcast relay worker that passes 'delivered' StatusCallback messages that have `broadcastId` from Twilio to Gambit Conversations `/import-message`.
- `yarn web`
- `yarn worker twilio-sms-broadcast-gambit-relay`
- Send curl request:
```
curl -X POST \
'http://localhost:5050/api/v1/webhooks/twilio-sms-broadcast?broadcastId=blink-test' \
-H 'authorization: Basic Ymxpbms6Ymxpbms=' \
-H 'content-type: application/json' \
-d '{
"To": "+15552222222",
"Body": "Boost a stranger'\'''\''s self-esteem with just a sticky note! \n\nWant to join Mirror Messages?\n\nYes or No",
"MessageStatus": "delivered",
"MessageSid": "SMXXX"
}'
```
- Notice worker logs. It should retry, as broadcastId is not defined
Pivotal …
> [#151266069] Gambit broadcast relay worker

- src/messages/CustomerIoUpdateCustomerMessage.js
- src/messages/UserMessage.js
- src/workers/CustomerIoUpdateCustomerWorker.js
- test/helpers/MessageFactoryHelper.js
- test/messages/CustomerIoUpdateCustomerMessage.test.js
- test/messages/UserMessage.test.js
- test/web/controllers/EventsWebController.test.js
This pull request adds support for SMS related fields in Customer.io!
📝 Renames `mobile_status` to `sms_status` to be consistent with naming in Northstar. Since we haven't been sending phone numbers to Customer.io, this should still be safe to change. (24fa2a0)
☎️ Adds support for the E.164-formatted `mobile` field. (be8c04c)
Let me know if there are any things I'm missing!
> Adds support for SMS-related fields.

- src/messages/CustomerIoUpdateCustomerMessage.js
- src/workers/CustomerIoUpdateCustomerWorker.js
- test/helpers/MessageFactoryHelper.js
- test/messages/CustomerIoUpdateCustomerMessage.test.js
This pull request adds some logic to determine whether a user is newly created by comparing their `created_at` and `updated_at` values, which means we'll be able to start sending user updates without automatically re-subscribing people.
We're currently assuming that `unsubscribed` is only relevant for users with email addresses, since we want to track SMS subscription status separately in the `sms_status` field. (Waiting to hear back from Customer.io to see if we need to do some extra work here!)
I updated the user returned from the `getValidUser` method to be "new" so that the existing tests continue to pass. If it makes sense, I'm also up for adding a few new test cases here for user updates & new users without email addresses.
> Set 'unsubscribed' in Customer.io for new email users.

- src/app/BlinkApp.js
- src/app/BlinkWebApp.js
- src/queues/TwilioSmsBroadcastGambitRelayQ.js
- src/queues/TwilioSmsInboundGambitRelayQ.js
- src/web/controllers/WebController.js
- src/web/controllers/WebHooksWebController.js
- test/web/controllers/WebHooksWebController.test.js
- Creates `/api/v1/webhooks/twilio-sms-inbound` to relay inbound sms traffic to Gambit Conversation's `/revieve-message`
- Created new helper function `WebController.sendOKNoContent()` that sends `204 No Content` which is usefull TwiML responses with no body
- Used `WebController.sendOKNoContent()` to reply to Twilio Status Callback and Inbound SMS webhooks
Pivotal [151620532](https://www.pivotaltracker.com/story/show/151620532)
> [#151620532] Implement /twilio-sms-inbound webhook for GamCon inbound sms relay

- Procfile
- src/app/BlinkWorkerApp.js
- src/workers/TwilioSmsInboundGambitRelayWorker.js
- test/workers/TwilioSmsInboundGambitRelayWorker.test.js
- Creates Gambit inbound sms relay worker that passes all Twilio Inbound Request URI messages Gambit Conversations `/recieve-message`. No data validation is imposed to this messages, except being a valid JSON.
- `yarn web`
- `yarn worker twilio-sms-inbound-gambit-relay`
- Send curl request:
```
curl -X POST \
'http://localhost:5050/api/v1/webhooks/twilio-sms-inbound' \
-H 'authorization: Basic Ymxpbms6Ymxpbms=' \
-H 'content-type: application/json' \
-d '{}'
```
Where data should be a valid payload sent from Twilio.
Pivotal [151620532](https://www.pivotaltracker.com/story/show/151620532)
Closes #119
> [#151620532] Implements Gambit inbound sms relay

- src/app/BlinkWebApp.js
- src/queues/QuasarCustomerIoEmailActivityQ.js
- src/web/controllers/EventsWebController.js
- test/.eslintrc.js
- test/helpers/MessageFactoryHelper.js
- test/web/controllers/EventsWebController.test.js
- test/web/controllers/WebHooksWebController.test.js
- Implements web endpoint `/api/v1/events/quasar-relay`
- Saves all JSON payloads received by the endpoint to `quasar-customer-io-email-activity` queue (a subject to change changed as described in #99)
- `yarn web`
- Send freeform JSON to `/api/v1/events/quasar-relay`
- Make sure you can see the payload in http://localhost:15672/#/queues/blink/customer-io-update-customer -> Get Messages
For now, `quasar-customer-io-email-activity` queue is used for a generic integration with Data consumer. It will be renamed to `data-prime` queue or `quasar-data-prime` soon, see #99.
Pivotal [#151022906](https://www.pivotaltracker.com/story/show/151022906)
A part of #127
> [#151022906] Send generic JSON payloads from web endpoint to a queue owned by Data team

- Procfile
- src/app/BlinkApp.js
- src/app/BlinkWorkerApp.js
- src/queues/GambitCampaignSignupRelayQ.js
- src/workers/GambitCampaignSignupRelayWorker.js
- test/web/controllers/EventsWebController.test.js
- test/workers/GambitCampaignSignupRelayWorker.test.js
- Creates `gambit-campaign-signup-relay` queue which recieves campiang signup messages
- Creates `gambit-campaign-signup-relay` worker which listenes for new messages in `gambit-campaign-signup-relay` queue and relayes them to Gambit Conversation in [specified](https://github.com/DoSomething/gambit-conversations/blob/master/documentation/endpoints/send-message.md) format
- Sign up for a Thor campaign which is enabled in Gambit Campaigns Staging
Pivotal [151266508](https://www.pivotaltracker.com/story/show/151266508)
Ref https://github.com/DoSomething/gambit-conversations/pull/155
> [#151266508] Send Rogue campaign signup events to Gambit Conversations

- src/app/BlinkWebApp.js
- src/web/controllers/WebController.js
- Improves logging of invalid and unparsed messages
- `yarn web`
- Request
```
curl -X POST \
http://localhost:5050/api/v1/events/user-create \
-H 'authorization: Basic Ymxpbms6Ymxpbms=' \
-H 'content-type: application/json' \
-d 1
```
Should show error:
```
2017-10-16T19:19:42.132Z app[]: at=warning application=blink env=development code=error_parsing_body request_id=a4ef7dd9-f59d-4a75-b63f-b1e31aa1180d method=POST host=localhost path=/api/v1/events/user-create fwd=::1 protocol=http Body parsing error.
```
- Request
```
curl -X POST \
http://localhost:5050/api/v1/events/user-create \
-H 'authorization: Basic Ymxpbms6Ymxpbms=' \
-H 'content-type: application/json' \
-d '{
"id": "just-no"
}'
```
Should show error:
``` …
```
> Improve logging of invalid messages

- src/workers/GambitCampaignSignupRelayWorker.js
- test/helpers/MessageFactoryHelper.js
- test/workers/GambitCampaignSignupRelayWorker.test.js
- Performs source filtering on Rogue signups in `GambitCampaignSignupRelayWorker`
See steps to reproduce manually in #152.
Pivotal [152052652](https://www.pivotaltracker.com/story/show/152052652)
Fixes #152
> [Finishes #152052652] Don't send Rogue signups to Gambit when they are created by Gambit

- src/lib/DelayLogic.js
- src/lib/Dequeuer.js
- src/lib/RetryManager.js
- src/messages/Message.js
- src/workers/GambitCampaignSignupRelayWorker.js
- src/workers/GambitChatbotMdataProxyWorker.js
- src/workers/GambitMessageDataRelayWorker.js
- src/workers/TwilioSmsBroadcastGambitRelayWorker.js
- src/workers/TwilioSmsInboundGambitRelayWorker.js
- test/helpers/HooksHelper.js
- test/lib/Dequeuer.test.js
- test/lib/RetryManager.test.js
- test/workers/GambitCampaignSignupRelayWorker.test.js
- test/workers/GambitChatbotMdataProxyWorker.test.js
- test/workers/GambitMessageDataRelayWorker.test.js
- test/workers/TwilioSmsBroadcastGambitRelayWorker.test.js
- test/workers/TwilioSmsInboundGambitRelayWorker.test.js
- Changes API of `RetryManager.retry()`, it's async now and resolves into actual retry results
- Adds helpers methods on Message class exposing `.meta.retryAttempt` field and its incrementation logic
- 100% unit test coverage for RetryManager
- Provides additional test helpers to use Queue classes in memory and not actually asserting queues in RabbitMQ, when useful
Pivotal [152113738](https://www.pivotaltracker.com/story/show/152113738)
> [#152113738] Test coverage for RetryManager

- package.json
- wercker.yml
Updates Node.js engine to 8.9.3.
This is a security release upgrade, read more https://nodejs.org/en/blog/vulnerability/december-2017-security-releases/
> Chore: update node to 8.9.3

- src/messages/CampaignSignupMessage.js
- src/messages/CampaignSignupPostMessage.js
- src/messages/CustomerIoUpdateCustomerMessage.js
- src/messages/CustomerIoWebhookMessage.js
- src/messages/CustomerioSmsBroadcastMessage.js
- src/messages/FetchMessage.js
- src/messages/FreeFormMessage.js
- src/messages/Message.js
- src/messages/TwilioStatusCallbackMessage.js
- test/unit/lib/Dequeuer.test.js
- test/unit/messages/Message.test.js
This PR makes it optional to create `fromCtx()` and `fromRabbitMessage()` from extending from `Message` class. Both these methods are moved to `Message` class itself, which dynamically figures out what concrete class to create.
Also, this PR will automatically save GET data to message metadata. Before that this only worked in `TwilioStatusCallbackMessage`
- `yarn test:full`
This feature depends on the property of `this` context inside of a static method to have `prototype` property that is the class on which static method is called.
For example:
```js
class Message {
static printClassName() {
console.log(this.prototype.constructor.name);
}
}
class SpecificMessage extends Message {}
SpecificMessage.printClassName(); // prints 'SpecificMessage'
```
> Refactoring: simplify concrete message classes

- .env.example
- Procfile
- config/gambit.js
- src/app/BlinkApp.js
- src/app/BlinkWebApp.js
- src/app/BlinkWorkerApp.js
- src/messages/CustomerioGambitBroadcastMessage.js
- src/queues/CustomerioGambitBroadcastQ.js
- src/web/controllers/WebHooksWebController.js
- src/workers/CustomerIoGambitBroadcastWorker.js
- src/workers/CustomerIoSmsBroadcastRelayWorker.js
- test/helpers/MessageFactoryHelper.js
- test/integration/web/controllers/WebHooksWebController.test.js
- test/unit/queues/CustomerioGambitBroadcastQ.test.js
First pass at a `CustomerIoGambitBroadcast` resource, based off of the `CustomerioSmsBroadcast`, to deliver broadcast messages via Gambit Conversations `POST /v2/messages?origin=broadcast` (https://github.com/DoSomething/gambit-conversations/pull/272)
🍔 for 💭 - 
* Went with `Gambit` instead of `Sms`, as ideally we'd add a platform parameter, to use one queue for broadcasts over multiple platforms (e.g. FB Messenger).
* I've named it with the CustomerIo prefix for now, but keep thinking about calling it `GambitBroadcast` vs `CustomerIoGambitBroadcast`.. which would make it more of an event than a webhook. Would each service that can send a broadcast get its own queue? (similar to previous naming decision on `GambitBroadcast` vs `GambitSmsBroadcast`
Cleanup TODOs for the future:
* After go …
> Gambit Broadcast webhook

- .gitignore
- package.json
- Updates the versioning that I missed in latest release.
- Adds `.wercker` files to the `.gitignore` list.
- 👀
> Bumped version to 2.0.1. Added .wercker to .gitignore

- package.json
- src/messages/CampaignSignupPostMessage.js
- src/messages/Message.js
- src/validations/campaignSignupPost.js
- src/web/controllers/EventsWebController.js
- test/helpers/MessageFactoryHelper.js
- test/integration/web/controllers/EventsWebController.test.js
- test/unit/messages/CampaignSignupPostMessage.test.js
- yarn.lock
It validates only a minimum set of required properties that the messaging team is expecting for successful segmentation. All other properties sent, aside from this subset of required props, are considered optional or nullable. More on which are considered required vs optional: [Blink Validation section](https://github.com/orgs/DoSomething/teams/team-bleed/discussions/13).
- Run the tests and get no errors:
- `cd` into your local Blink repo.
- `docker-compose up -d`
- `yarn test:full`
- `docker-compose down`
Fixes #125 
Fixes #173 
Removes the quantity requirement for this route mentioned in #174 
Fixes part 1 of the Validation tasks in [Pivotal #154736700](https://www.pivotaltracker.com/story/show/154736700)
> removed unnecessary validations in CampaignSignupPost Message.

- config/gambit.js
- src/workers/CustomerIoGambitBroadcastWorker.js
- src/workers/CustomerIoSmsBroadcastRelayWorker.js
- src/workers/GambitCampaignSignupRelayWorker.js
- src/workers/TwilioSmsBroadcastGambitRelayWorker.js
- src/workers/TwilioSmsInboundGambitRelayWorker.js
_Note_: This can't be deployed to production until https://github.com/DoSomething/gambit-conversations/pull/283 is merged and deployed. Ok for testing on staging, as #283 has been deployed to staging for review.
---
Updates the `TwilioSmsInboundGambitRelayWorker` to post inbound Twilio messages to `/v2/messages` per https://github.com/DoSomething/gambit-conversations/pull/283 and some cleanup:
* Fixes `conversationsApiKey` typo.
* Removes pre-TGM  `baseUrl` and `apiKey` properties that posted to Gambit Campaigns, adds a `conversations` object to the Gambit config to group Gambit services. 
* Renames `baseUri` to `baseURL`, previous Gambit `baseURL` as `v1BaseURL`
> Post Twilio messages to Conversations v2

- src/messages/FreeFormMessage.js
It overrides the validation method in FreeFromMessage to allow all keys, including those that contain `null` values.
The [latest changes](https://github.com/DoSomething/blink/pull/191) to add frictionless validation to Campaign Signup Post messages had the side effect of restricting `null` values for all Messages. The `/quasar-relay` route contract to other apps is that it should be able to consume any valid JSON data sent to it, the last changes broke that contract. This PR fixes it.
cc @DFurnes @sheyd 
- 👀
> Override validate method inside FreeFormMessage

- src/messages/CampaignSignupPostMessage.js
- src/messages/CustomerIoUpdateCustomerMessage.js
- src/messages/Message.js
- src/messages/UserMessage.js
- src/validations/userCreateAndUpdate.js
- src/web/controllers/EventsWebController.js
- src/workers/CustomerIoUpdateCustomerWorker.js
- test/helpers/MessageFactoryHelper.js
- test/helpers/MessageValidationHelper.js
- test/unit/messages/CustomerIoUpdateCustomerMessage.test.js
- test/unit/messages/UserMessage.test.js
It validates only a minimum set of required properties that the messaging team is expecting for successful segmentation. All other properties sent, aside from this subset of required props, are considered optional or nullable. The Required properties are:
- id (northstar_id)
- updated_at
- created_at
- email OR mobile
- Run the tests and get no errors:
- `cd` into your local Blink repo.
- `docker-compose up -d`
- `yarn test:full`
- `docker-compose down`
Fixes `last_messaged_at` bug [Pivotal #152901264](https://www.pivotaltracker.com/story/show/152901264)
Fixes `sms_paused` bug [Pivotal #153457736](https://www.pivotaltracker.com/story/show/153457736)
> Implement minimum validations in UserMessage

- package.json
- src/validations/userCreateAndUpdate.js
Removes validation on existence of `email` or `mobile` on user create/update events. Unblocks GDPR script.
> remove email or mobile validation in user-create

- src/workers/GambitCampaignSignupRelayWorker.js
It switches the property `platform` back to `source` when sending the payload of the signup event to G-Conversations.
- 👀
> Fixes bug that is preventing external signup messages from being delivered to users.

- config/app.js
- config/env/override-production.js
- package.json
- src/app/BlinkWebApp.js
- src/web/middleware/enforce-https.js
- start.js
- test/.eslintrc.js
- test/unit/web/middleware/enforce-https.test.js
- yarn.lock
It adds a middleware that will redirect any GET and HEAD requests to `https://`. Other requests like POSTs will return a `403`. Only while in the **production** environment. Local development will not be impacted.
NOTES:
There is a chance that this update will break other apps that are sending requests to Blink not using the HTTPS protocol. I have to check if it's just a matter of updating the ENV variable in those services first!
- 👀 
- Run all tests
Blink's item in [Pivotal#159114978](https://www.pivotaltracker.com/story/show/159114978)
> Enforces HTTPS in production

- config/env/override-staging.js
- src/messages/CustomerIoUpdateCustomerMessage.js
- test/unit/messages/CustomerIoUpdateCustomerMessage.test.js
- Passes along the `unsubscribed` value if it exist in the payload to `/user-create` events route.
- 👀 
- Run all tests
> Accept `unsubscribed` when creating new user in NS

- config/messages/CustomerIoWebhookMessage.js
- package.json
- src/app/BlinkApp.js
- src/messages/CustomerIoWebhookMessage.js
- src/queues/QuasarCustomerIoEmailActivityQ.js
- src/queues/QuasarCustomerIoEmailUnsubscribedQ.js
- src/web/controllers/EventsWebController.js
- src/web/controllers/WebHooksWebController.js
- test/integration/web/controllers/WebHooksWebController.test.js
- test/unit/queues/QuasarCustomerIoEmailActivityQ.test.js
It makes some changes to queue bindings so that C.io email activity requests continue to be routed to the `QuasarCustomerIoEmailActivity` queue via the `*.event.quasar` routing key. At the same time, adding the ability to copy the `email_unsubscribed` events to the `QuasarCustomerIoEmailUnsubscribed` queue via the `email-unsubscribed.event.quasar` routing key.
- 👀 
- Pass all tests
> Feature/email subscription - Queue and routing

- src/lib/Dequeuer.js
- src/messages/Message.js
- src/timers/RedisRetriesRepublishTimerTask.js
- src/web/controllers/WebController.js
- src/workers/CustomerIoTrackEventWorker.js
- src/workers/CustomerIoUpdateCustomerWorker.js
It requires a transformer to be passed to the `Message.toString()` functions in order to transform its payload instead of using the removePII transformer by default.
This fixes the bug where we were compulsively stripping PII from all message payloads by default. Because in order to publish a message's payload to our queues we need to convert it to a string. The `Message.toString()` method was called right before publishing, stripping the PII for us too!
- test updating PII in `Admin-qa` and seeing the profile change in C.io.
> Fixes PII being removed before enqueueing messages

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- src/messages/CustomerIoGambitBroadcastMessage.js
- src/workers/CustomerIoGambitBroadcastWorker.js
- src/workers/lib/helpers/gambit-conversations.js
- test/helpers/MessageFactoryHelper.js
- test/integration/web/controllers/EventsWebController.test.js
- test/integration/web/controllers/WebHooksWebController.test.js
- test/integration/workers/CustomerIoGambitBroadcastWorker.test.js
- test/unit/messages/CampaignSignupMessage.test.js
- test/unit/messages/CampaignSignupPostMessage.test.js
- test/unit/messages/CampaignSignupPostReviewMessage.test.js
- test/unit/messages/CustomerIoGambitBroadcastMessage.test.js
- test/unit/messages/CustomerIoSmsStatusActiveMessage.test.js
- test/unit/messages/CustomerIoUpdateCustomerMessage.test.js
- test/unit/messages/CustomerIoWebhookMessage.test.js
- test/unit/messages/TwilioOutboundStatusCallbackMessage.test.js
- test/unit/messages/UserMessage.test.js
- test/unit/workers/CustomerIoEmailUnsubscribedNorthstarWorker.test.js
- test/unit/workers/CustomerIoGambitBroadcastWorker.test.js
- test/unit/workers/CustomerIoSmsStatusActiveWorker.test.js
- test/unit/workers/GambitCampaignSignupRelayWorker.test.js
- test/unit/workers/TwilioSmsInboundGambitRelayWorker.test.js
- test/unit/workers/lib/lib-helpers/gambit-conversations.test.js
- Makes `mobile` an optional parameter for the `/api/v1/webhooks/customerio-gambit-broadcast` webhook.
- Adds check for `mobile`. If found, it sends the request to the new `origin=broadcastLite` route.
- Cleans up naming in the MessageFactory test helper
- 👀 
- Run all tests
- This modification is necessary to allow the use of the new `origin=broadcastLite` route while keeping backwards compatibility for the `origin=broadcast` route.
Unblocks future work based on https://github.com/DoSomething/gambit-conversations/pull/407
Fixes a task in Pivotal [Card#160585940](https://www.pivotaltracker.com/story/show/160585940)
> make mobile optional for broadcasts [pr]

- config/workers/lib/helpers/northstar.js
- src/workers/NorthstarRelayBaseWorker.js
- It modifies the sent payload to Northstar from `{ "email_frequency": "stop" }` to `{ "email_subscription_status": false }` when relaying email unsubscribed events to Northstar.
- It exposes retry logs when an update to a member's `email_subscription_status` fails and it's retried.
- 👀 
Complementing changes for https://github.com/DoSomething/northstar/pull/824
> update email subscription status property and value [pr]

- Procfile
- config/lib/helpers/logger/transformers/leanify.js
- src/app/BlinkApp.js
- src/app/BlinkWorkerApp.js
- src/messages/PasswordResetMessage.js
- src/queues/CustomerIoPasswordResetQ.js
- src/validations/passwordReset.js
- src/web/controllers/EventsWebController.js
- src/workers/CustomerIoPasswordResetWorker.js
- test/helpers/MessageFactoryHelper.js
- test/integration/web/controllers/EventsWebController.test.js
- test/unit/messages/PasswordResetMessage.test.js
Adds a new API endpoint to create `password_reset` events in Customer.io, which we'll eventually use for Customer.io event triggered campaigns for sending Forgot Password emails from Northstar, or Account Activation emails from Chompy.
* Adds new `customer-io-password-reset` queue and corresponding worker
Here's an example request for localhost:
```
curl -X POST \
http://localhost:5050/api/v1/events/user-password-reset \
-H 'Authorization: Basic [removed]=' \
-H 'Content-Type: application/json' \
-d '{
"user_id": "yourNorthstarId",
"subject": "Reset Password",
"body": "<h3>Hello!</h3><p>You are receiving this email because we received a password reset request for your DoSomething.org account. Here is the link to reset your password: http://puppetsloth.com</p>",
"url": …
```
> Adds new /api/v1/events/user-password-reset

- src/messages/CallToActionEmailMessage.js
- src/validations/callToActionEmail.js
- test/helpers/MessageFactoryHelper.js
- test/unit/messages/CallToActionEmailMessage.test.js
* Adds an optional `type` parameter for creating a `call_to_action_email` event in Customer.io. This will eventually be changed to required once Northstar starts sending one.
* Changes properties from required to optional: `intro`, `outro`, `subject,`, and `actionText` per https://github.com/orgs/DoSomething/teams/team-bleed/discussions/34
Verify `type` attribute appears in a Customer.io `call_to_action_email` event when including in a `POST /v1/events/user-call-to-action-email` request.
Because so many of the rules for who to send to are defined in our Customer.io environments, I think it's overall easier to maintain the email content from within Customer.io as well, instead of the apps that create the events.
https://www.pivotaltracker.com/story/show/163779567
> Adds CallToActionEmailMessage.type

- src/validations/callToActionEmail.js
- test/helpers/MessageFactoryHelper.js
- test/integration/web/controllers/EventsWebController.test.js
Changes `type` parameter in a `call_to_action_email` Customer.io event as required instead of optional. This type parameter is what's used to determine what email to send via [Event Triggered Campaigns](http://docs.dosomething.org/customer-io#call-to-action-email).
👀 
We're looking to start a new type of `call_to_action_email` event for opt-ins from Content pages in Phoenix - sounds like a good time to start requiring this field now that Northstar sends over per https://github.com/DoSomething/northstar/pull/847 (cc @katiecrane)
> Require CallToActionEmail.type parameter

- src/workers/CustomerIoEmailUnsubscribedNorthstarWorker.js
This pull request wraps the `body` for the Northstar unsubscribe request in `JSON.stringify` so that it isn't sent as a rather unhelpful `[object Object]` string.
Compare the change in e27c4b9 with [node-fetch's documentation](https://github.com/bitinn/node-fetch#post-with-json). We already set the `Content-Type: application/json` header in `northstarHelper.getRequestHeaders`, so the only necessary change was stringifying the object.
This means we haven't been properly setting `email_subscription_status` for any users that hit the "unsubscribe" link in an email footer, so we'll need to [re-import those updates](https://www.pivotaltracker.com/story/show/166361521) after deploying this fix.
Fixes Pivotal [#166361430](https://www.pivotaltracker.com/story/show/166361430).
> Properly encode JSON body for Northstar API call.

- src/errors/BlinkSendToDLXError.js
- src/lib/Dequeuer.js
- src/messages/CustomerIoWebhookMessage.js
- src/workers/CustomerIoEmailUnsubscribedNorthstarWorker.js
- test/helpers/MessageFactoryHelper.js
- test/integration/web/controllers/WebHooksWebController.test.js
- wercker.yml
- When a `user_unsubscribed` C.io event timestamp's is between `2020-04-01` and `2020-05-05`. It sends the event into the `blink-dlx` (dead letter) queue. Without updating the user's profile in Northstar.
- This is meant to be a temporary patch to enable backfilling C.io's email events for the month of April and a few days of May. Will be removed after the backfill!
- Dead letter exchange is being setup through the RabbitMQ Management plugin as a Policy instead of passed arguments when asserting queues in code.
- `blink-dlx` dead letter was setup manually for simplicity.
- 👀 
- Run tests (if dev setup)
Unblocks backfill for Pivotal [Card#172585118](https://www.pivotaltracker.com/story/show/172585118)
Fixes Pivotal [Card#172654252](https://www.pivotaltracker.com/story/show/172654252)
> Cio northstar unsubscribed events patch

- src/messages/CustomerIoWebhookMessage.js
- src/workers/CustomerIoEmailUnsubscribedNorthstarWorker.js
- test/integration/web/controllers/WebHooksWebController.test.js
Fixes logic that checks if the C.io `user_unsubscribed` event's timestamp falls within the backfill date range.
It adds a new `getEventTimestampInMilliseconds` method to get Unix Timestamp (seconds) in milliseconds.
Fixes Pivotal [Card#172782220](https://www.pivotaltracker.com/story/show/172782220)
> Fixes parsing of C.io event timestamp to correct format

- src/messages/CustomerIoGambitBroadcastMessage.js
- src/workers/CustomerIoGambitBroadcastWorker.js
- test/integration/web/controllers/WebHooksWebController.test.js
This PR adds support for the new parameters that will be passed to a Gambit `POST /v2/messages?origin=broadcastLite` request per https://github.com/DoSomething/gambit/pull/552.
It also temporarily disables validation on the `northstarId` field, to eventually require a `userId` field instead.
👀 
🐰 
[Pivotal #177168378](https://www.pivotaltracker.com/story/show/177168378)
> Updates CustomerIoGambitBroadcastMessage schema

- package.json
- src/workers/CustomerIoEmailUnsubscribedNorthstarWorker.js
- test/integration/web/controllers/WebHooksWebController.test.js
- wercker.yml
This pull request suppresses any incoming Customer.io webhook events that don't have `data.customer_id`. This should fix some errors we were seeing on incoming messages from users whose Customer.io accounts we'd deleted. 
🧶 I upgraded the pinned Yarn version in d211b46 to match what I'm running locally (rather than try to downgrade my own yarn to the exact pinned release). Is there a better way for me manage this on my end?
🩹 Removed a patch for an [old issue](https://www.pivotaltracker.com/story/show/172585118) that's since been resolved in 134e1c4.
🔇 If we don't have a `userId`, then suppress to bypass making a Northstar request & not retry. ba407ad
This application still uses Wercker for CI, which we haven't configured for [their new rate …
> Fix Customer.io webhooks for deleted customers.
